### PR TITLE
Updated ROS 2 commands

### PR DESCRIPTION
**Pull request by horverno**
Changed the ROS 1 commands to its ROS 2 counterpart.

### CODE REVIEW

**Review by bilgineroral — APPROVED** [review]
Same worked for my Humble installation

**Review by bilgineroral — CHANGES_REQUESTED** [review]
Also update the test data links with https://drive.proton.me/urls/Z83QCWKZWW#bMIqDh02AJZZ and https://drive.proton.me/urls/7NQSK9DXJ0#gZ9yjGNrDBgG (they are not updated in the feature/ros2 branch)

**Comment by horverno** [comment]
hi @bilgineroral i tried to use the files (`trees-dome.bag`, `aggressive_spinning.bag`) but they seem like an old ROS 1 format which is not ROS 2 compatible.

What do you suggest in this case? 

``` r
$ ros2 bag info /mnt/c/bag/aggressive_spinning.bag

[ERROR] [rosbag2_storage]: No storage id specified, and no plugin found that could open URI
```

**Comment by bilgineroral** [comment]
@horverno you can use the [rosbags](https://pypi.org/project/rosbags/)  package to convert ros1 bags to ros2 bags, or vice versa. example usage would be `rosbags-convert --src aggressive_spinning.bag  --dst output` and you'll find your ros2 bag in a folder named `output`.

**Comment by kennyjchen** [comment]
Thank you! Merged.

**Pull request merged**
